[package]
name = "fibonacci-circuit"
version = "0.1.0"
edition = "2021"

default-run = "example1"

# multiple binary
[[bin]]
name = "example1"
path = "src/example1.rs"

[dependencies]
halo2_proofs = "0.1.0"